damage/urls.py
from django.urls import path

from . import views

app_name = 'damage'

urlpatterns = [
	# ex: /
    path('', views.index, name='index'),
    
    # ex: /detail/5/
    path('detail/<int:weapon_id>/', views.detail, name='detail'),
    
    # ex: /5/results/
    path('compare/<int:weapon_id1>/<int:weapon_id2>/', views.compare, name='compare'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('damage/', include('damage.urls')),
    path('shopper/', include('shopper.urls')),
    path('admin/', admin.site.urls),
]

shopper/urls.py
from django.urls import path

from . import views

app_name = 'shopper'

urlpatterns = [
	# ex: /
    path('', views.index, name='index'),
]

damage/models.py
from django.db import models

class Weapon(models.Model):
	TYPE_PISTOL = 'pistol'
	TYPE_SHOTGUN = 'shotgun'
	TYPE_RIFLE = 'rifle'
	TYPE_HEAVY = 'heavy gun'
	TYPE_MELEE = 'melee'
	TYPE_THROWN = 'thrown'
	
	WEAPON_TYPES = (
		(TYPE_PISTOL, 'Pistol'),
		(TYPE_SHOTGUN, 'Shotgun'),
		(TYPE_RIFLE, 'Rifle'),
		(TYPE_HEAVY, 'Heavy Gun'),
		(TYPE_MELEE, 'Melee'),
		(TYPE_THROWN, 'Thrown'),
	)
	
	AMMO_NONE = 'None'
	AMMO_5MM = 'Ammo5mm'
	AMMO_556 = 'Ammo556'
	AMMO_308 = 'Ammo308Caliber'
	AMMO_308ULTRACITE = 'Ammo308Caliber_AntiScorchBeast'
	AMMO_38 = 'Ammo38Caliber'
	AMMO_10MM = 'Ammo10mm'
	AMMO_44 = 'Ammo44'
	AMMO_45 = 'Ammo45Caliber'
	AMMO_50 = 'Ammo50Caliber'
	AMMO_50BALL = 'Ammo50CaliberBall'
	AMMO_SHOTGUNSHELL = 'AmmoShotgunShell'
	AMMO_2MMEC = 'Ammo2mmEC'
	AMMO_FUSIONCELL = 'AmmoFusionCell'
	AMMO_FUSIONCORE = 'AmmoFusionCore'
	AMMO_GAMMACELL = 'AmmoGammaCell'
	AMMO_PLASMACARTRIDGE = 'AmmoPlasmaCartridge'
	AMMO_PLASMACORE = 'AmmoPlasmaCore'
	AMMO_CRYOCELL = 'AmmoCryoCell'
	AMMO_ALIENBLASTER = 'AmmoAlienBlaster'
	AMMO_CANNONBALL = 'AmmoCannonBall'
	AMMO_RRSPIKE = 'AmmoRRSpike'
	AMMO_FLAMERFUEL = 'AmmoFlamerFuel'
	AMMO_40MMGRENADE = 'AmmoGrenadeLauncher'
	AMMO_MISSILE = 'AmmoMissile'
	AMMO_MININUKE = 'AmmoFatManMiniNuke'
	
	AMMO_TYPES = (
		(AMMO_NONE, 'None'),
		(AMMO_5MM, '5mm'),
		(AMMO_556, '5.56mm'),
		(AMMO_308, '.308'),
		(AMMO_308ULTRACITE, '.308 Ultracite'),
		(AMMO_38, '.38'),
		(AMMO_10MM, '10mm'),
		(AMMO_44, '.44'),
		(AMMO_45, '.45'),
		(AMMO_50, '.50'),
		(AMMO_50BALL, '.50 ball'),
		(AMMO_SHOTGUNSHELL, 'Shotgun Shell'),
		(AMMO_2MMEC, '2mm EC'),
		(AMMO_FUSIONCELL, 'Fusion Cell'),
		(AMMO_FUSIONCORE, 'Fusion Core'),
		(AMMO_GAMMACELL, 'Gamma Cell'),
		(AMMO_PLASMACARTRIDGE, 'Plasma Cartridge'),
		(AMMO_PLASMACORE, 'Plasma Core'),
		(AMMO_CRYOCELL, 'Cryo Cell'),
		(AMMO_ALIENBLASTER, 'Alien Blaster'),
		(AMMO_CANNONBALL, 'Cannonball'),
		(AMMO_RRSPIKE, 'Railway Spike'),
		(AMMO_FLAMERFUEL, 'Flamer Fuel'),
		(AMMO_40MMGRENADE, '40mm Grenade'),
		(AMMO_MISSILE, 'Missile'),
		(AMMO_MININUKE, 'Mini Nuke'),
	)

	name = models.CharField(max_length=64)
	type = models.CharField(max_length=32, choices=WEAPON_TYPES)
	level = models.PositiveSmallIntegerField()
	damage = models.PositiveSmallIntegerField()
	ammo = models.CharField(max_length=32, choices=AMMO_TYPES)
	automatic = models.BooleanField(default=False)
	explosive = models.BooleanField(default=False)
	speed = models.DecimalField(max_digits=4, decimal_places=2)
	range = models.DecimalField(max_digits=5, decimal_places=2)
	strength_factor = models.DecimalField(max_digits=3, decimal_places=2)
	accuracy = models.DecimalField(max_digits=4, decimal_places=2)
	weight = models.DecimalField(max_digits=4, decimal_places=2)

	def __str__(self):
		return f"{self.name} (level {self.level})"

shopper/models.py
from django.db import models

class Location(models.Model):
	name = models.CharField(max_length=64)
	description = models.CharField(blank=True, max_length=128)
	coord_x = models.IntegerField()
	coord_y = models.IntegerField()
	
	def __str__(self):
		return f"{self.name} ({self.coord_x}, {self.coord_y})"
	
class Ingredient(models.Model):
	name = models.CharField(max_length=64)
	
	def __str__(self):
		return f"{self.name}"
	
class Recipe(models.Model):
	name = models.CharField(max_length=64)
	level = models.PositiveSmallIntegerField()
	location = models.ManyToManyField(Location)
	ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient', through_fields=('recipe', 'ingredient'))

	def __str__(self):
		return f"{self.name} (Level {self.level})"
		
class RecipeIngredient(models.Model):
	recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
	ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
	count = models.PositiveSmallIntegerField()
	
	def __str__(self):
		return f"{self.recipe} - {self.ingredient} ({self.count})"

damage/views.py
from django.shortcuts import render
from django.template import loader

from .models import Weapon


def index(request):
    weapon_list = Weapon.objects.all()
    
    context = {
        'weapon_list': weapon_list,
    }
    
    return render(request, 'damage/index.html', context)
    
def detail(request, weapon_id):
    weapon = Weapon.objects.get(id=weapon_id)
        
    context = {
        'weapon': weapon,
        'weapon_dps': weapon.damage * weapon.speed,
    }

    return render(request, 'damage/detail.html', context)
    
def compare(request, weapon_id1, weapon_id2):
    weapon1 = Weapon.objects.get(id=weapon_id1)
    weapon2 = Weapon.objects.get(id=weapon_id2)
   
    context = {
        'weapon1': weapon1,
        'weapon2': weapon2,
    }

    return render(request, 'damage/compare.html', context)

shopper/views.py
from django.shortcuts import render
from django.template import loader

from .models import Recipe


def index(request):
    recipe_list = Recipe.objects.all()
    
    context = {
        'recipe_list': recipe_list,
    }
    
    return render(request, 'shopper/index.html', context)

damage/templates/damage/compare.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Comparing {{ weapon1.name }} (Level {{ weapon1.level }}) and {{ weapon2.name }} (Level {{ weapon2.level }})</title>
    </head>
    <body>
        <p>{{ weapon1.name }} (Level {{ weapon1.level }}). {{ weapon1.damage }} damage.
        <p>{{ weapon2.name }} (Level {{ weapon2.level }}). {{ weapon2.damage }} damage.
    </body>
</html>

damage/templates/damage/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{{ weapon.name }} (Level {{ weapon.level }})</title>
    </head>
    <body>
        {{ weapon.name }} (Level {{ weapon.level }}). {{ weapon_dps }} DPS.
    </body>
</html>

damage/templates/damage/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Index</title>
    </head>
    <body>
        {% if weapon_list %}
            <ul>
            {% for weapon in weapon_list %}
                <li><a href="{% url 'damage:detail' weapon.id %}">{{ weapon }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No weapons found.</p>
        {% endif %}
    </body>
</html>

shopper/templates/shopper/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Index</title>
    </head>
    <body>
        {% if recipe_list %}
            <ul>
            {% for recipe in recipe_list %}
                <li>{{ recipe }}</li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No recipes found.</p>
        {% endif %}
    </body>
</html>